version: '3.8'

services:
  redis7:
    image: redis:7.4
    command: "redis-server --enable-debug-command yes --protected-mode no"
    ports:
      - "6379:6379"
    networks:
      - redis-network

  pwd-redis8:
    image: redis:8
    command: "redis-server --protected-mode no --requirepass redis-password"
    ports:
      - "16380:6379"
    networks:
      - redis-network

  redis-exporter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9121:9121"
    environment:
      - REDIS_ADDR=redis://redis7:6379
      - REDIS_EXPORTER_LOG_LEVEL=INFO
    depends_on:
      - redis7
    networks:
      - redis-network

networks:
  redis-network:
    driver: bridge

